[book]
authors = ["Oliver Nordbjerg"]
language = "en"
multilingual = false
src = "src"
title = "Foundry Book"
description = "A book on all things Foundry"

[[output.i18n.translations]]
language = "zh"
translators = ["https://www.github.com/coldstar1993"]
title = "Foundry 中文"
